### ISSUE TITLE
Contents of <code> elements cut off

### ISSUE THREAD

**Issue by scienceplease** [mesonbuild/mesonbuild.github.io#6]
Across documentation, the contents of \<code\> elements are cut off and do not text wrap source content. For example, compare the comment strings of keyword arguments for [add_project_arguments()](https://mesonbuild.com/Reference-manual_functions.html#add_project_arguments) to their [complete descriptions](https://github.com/mesonbuild/meson/blob/master/docs/yaml/functions/add_global_arguments.yaml).

**Comment by jpakkane** [comment]
This repository is only used to host the web pages (nobody actually even tracks errors filed here, I saw this by accident). Please file all issues against the main Meson repo. Thanks.
